# Generated by Django 4.0.7 on 2023-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x2_h', models.BooleanField()),
                ('xn2_h', models.BooleanField()),
                ('y2_h', models.BooleanField()),
                ('x2_count', models.IntegerField(default=0)),
                ('xn2_count', models.IntegerField(default=0)),
                ('y2_count', models.IntegerField(default=0)),
                ('x2_last_true', models.DateTimeField(blank=True, null=True)),
                ('x2_last_false', models.DateTimeField(blank=True, null=True)),
                ('xn2_last_true', models.DateTimeField(blank=True, null=True)),
                ('xn2_last_false', models.DateTimeField(blank=True, null=True)),
                ('y2_last_true', models.DateTimeField(blank=True, null=True)),
                ('y2_last_false', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_1_h', models.BooleanField()),
                ('x_n1_h', models.BooleanField()),
                ('y1_h', models.BooleanField()),
                ('yn1_h', models.BooleanField()),
                ('x_1_count', models.IntegerField(default=0)),
                ('x_n1_count', models.IntegerField(default=0)),
                ('y1_count', models.IntegerField(default=0)),
                ('yn1_count', models.IntegerField(default=0)),
                ('x_1_last_true', models.DateTimeField(blank=True, null=True)),
                ('x_1_last_false', models.DateTimeField(blank=True, null=True)),
                ('x_n1_last_true', models.DateTimeField(blank=True, null=True)),
                ('x_n1_last_false', models.DateTimeField(blank=True, null=True)),
                ('y1_last_true', models.DateTimeField(blank=True, null=True)),
                ('y1_last_false', models.DateTimeField(blank=True, null=True)),
                ('yn1_last_true', models.DateTimeField(blank=True, null=True)),
                ('yn1_last_false', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
