# Generated by Django 4.0.7 on 2023-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyl1_X1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl1_XN1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl1_Y1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl1_YN1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl2_X2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl2_XN2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cyl2_Y2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('initial', models.BooleanField(default=False)),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemStateTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('time_switch', models.DateTimeField(auto_now_add=True)),
                ('time_worked', models.DurationField(null=True)),
            ],
        ),
    ]
