# Generated by Django 4.0.7 on 2023-06-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_cyl1_x1_cyl1_xn1_cyl1_y1_cyl1_yn1_cyl2_x2_cyl2_xn2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuxiliaryStateHistory',
        ),
        migrations.DeleteModel(
            name='MainStateHistory',
        ),
    ]
