# Generated by Django 4.0.6 on 2023-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y1', models.BooleanField()),
                ('yn1', models.BooleanField()),
            ],
        ),
    ]
