# Generated by Django 4.0.7 on 2023-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryCylinderStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x2', models.BooleanField()),
                ('xn2', models.BooleanField()),
                ('y2', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MainCylinderStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('x_1', models.BooleanField()),
                ('x_n1', models.BooleanField()),
                ('y1', models.BooleanField()),
                ('yn1', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='StateModel',
        ),
    ]
