# Generated by Django 4.0.7 on 2023-06-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaAPI', '0002_auxiliarycylinderstatemodel_maincylinderstatemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xauto', models.BooleanField()),
                ('xnext', models.BooleanField()),
                ('xpause', models.BooleanField()),
                ('xreset', models.BooleanField()),
                ('xrun', models.BooleanField()),
                ('xstep', models.BooleanField()),
            ],
        ),
    ]
