# Generated by Django 4.0.7 on 2023-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaAPI', '0003_systemstatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpause_desired', models.BooleanField()),
            ],
        ),
    ]
